# Necessary Imports

In [1]:
import numpy as np
import pandas as pd

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

In [ ]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import regex as re
from bs4 import BeautifulSoup
import time

# Getting Product Links from a Category Page

In [ ]:
# To open a new window: webdriver.Chrome(here pass the driver as a service)
# we need to create a object of a service class so that we can pass it to open a chrome window 
s=Service("C:/Users/Tanvir Ahmed/Downloads/chromedriver-win64/chromedriver.exe")
driver = webdriver.Chrome(service=s)
#after opening the window, searching for the link
driver.get('https://www.zazzle.com/s/bow+graduation+invitations?st=orderitemcount_month')
time.sleep(2) #wait 2 seconds
driver.execute_script("window.scrollTo(0, document.body.scrollHeight)") #scroll to the bottom to load all product
time.sleep(3)
page=driver.page_source #getting the source code of that loaded page
soup = BeautifulSoup(page,'lxml') #create a soup object to parse it, to get all products link
driver.quit() #close the window

In [ ]:
links=soup.find_all('a',{'class':'Link Link--marketplaceTheme SearchResultsGridCell2_link'}) #getting all product links available in the page by selecting specific class
link=[]
for i in range(0,len(links),2): #there are double link for a single product scrapped, that's why I just took every alternatinve links
    link.append(links[i]['href']) #getting the only links
link

['https://www.zazzle.com/pink_bow_photo_2025_graduation_invitation-256055896693503895',
 'https://www.zazzle.com/pink_bow_photo_graduation_party_invitation-256093504405710144',
 'https://www.zazzle.com/wildflower_pink_bow_graduation_invitation-256216092353790857',
 'https://www.zazzle.com/trendy_modern_photo_graduation_invitation-256920141544615649',
 'https://www.zazzle.com/elegant_black_bow_photo_grad_party_invitation-256525922731407841',
 'https://www.zazzle.com/arch_pink_bow_photo_graduation_party_invitation-256286770993629234',
 'https://www.zazzle.com/modern_trendy_pink_bow_graduation_cap_graduation_invitation-256039033918865893',
 'https://www.zazzle.com/wildflower_bow_graduation_party_photo_collage_invitation-256845528064435196',
 'https://www.zazzle.com/modern_elegant_pink_bow_graduation_cap_graduation_invitation-256204289868702558',
 'https://www.zazzle.com/black_bow_photo_graduation_invitation-256161264020359462',
 'https://www.zazzle.com/pink_bow_graduation_invitation-256959990670693750',
 'https://www.zazzle.com/modern_elegant_blue_bow_arch_photo_graduation_invitation-256872765486192820',
 'https://www.zazzle.com/modern_class_of_2026_photo_graduation_party_invitation-256835365265336742',
 'https://www.zazzle.com/wildflower_pink_bow_graduation_party_invitation-256538660526725744',
 'https://www.zazzle.com/pink_bow_three_photo_graduation_2025_invitation-256226014616658243',
 'https://www.zazzle.com/modern_elegant_trendy_pink_bow_photo_graduation_invitation-256654751266676829',
 'https://www.zazzle.com/elegant_blue_hydrangea_bow_ribbon_graduation_party_invitation-256873987968869972',
 'https://www.zazzle.com/wildflower_bow_graduation_invitation-256229209416312580',
 'https://www.zazzle.com/ribbon_graduation_3_letter_pink_monogram_crest_invitation-256863813810667935',
 'https://www.zazzle.com/pink_bow_vertical_script_graduation_invitation-256381719451539049',
 'https://www.zazzle.com/pink_bow_photo_graduation_party_invitation-256165396486096181',
 'https://www.zazzle.com/wildflower_bow_graduation_invitation-256403285902415027',
 'https://www.zazzle.com/modern_trendy_black_bow_graduation_party_invitation-256169133785508105',
 'https://www.zazzle.com/trendy_pink_bow_coquette_5_photo_graduation_party_invitation-256319801740686067',
 'https://www.zazzle.com/pink_bow_coquette_graduation_cap_thank_you_cards-256611545465090431',
 'https://www.zazzle.com/pink_coquette_nurse_graduation_invitation-256373911079655220',
 'https://www.zazzle.com/pink_coquette_bow_graduation_party_invitation-256798805520746605',
 'https://www.zazzle.com/modern_trendy_black_bow_graduation_party_invitation-256148454603653003',
 'https://www.zazzle.com/pink_bow_photo_graduation_invitation-256268419239254115',
 'https://www.zazzle.com/trendy_black_bow_ribbon_5_photo_graduation_party_invitation-256185528680769971',
 'https://www.zazzle.com/sweet_pinstriped_black_bow_graduation_invitation-256335053031814352',
 'https://www.zazzle.com/modern_elegant_trendy_stylish_black_bow_graduation_acrylic_invitations-256403584163777976',
 'https://www.zazzle.com/modern_trendy_black_bow_graduation_party_invitation-256800061660003110',
 'https://www.zazzle.com/blue_coquette_nurse_graduation_invitation-256955246647196426',
 'https://www.zazzle.com/coquette_pink_bow_shabby_chic_graduation_party_invitation-256318595421123537',
 'https://www.zazzle.com/trendy_pink_bow_photo_graduation_invitation-256244211359382208',
 'https://www.zazzle.com/elegant_red_bow_graduation_party_invitation-256291067936097248',
 'https://www.zazzle.com/elegant_coquette_bow_graduation_3_photos_invitation-256319693600478060',
 'https://www.zazzle.com/gold_and_black_coquette_nurse_graduation_rn_invitation-256732472283210948',
 'https://www.zazzle.com/wildflower_graduation_party_return_address_label-256799586037391857',
 'https://www.zazzle.com/modern_pink_bow_qr_code_college_fund_graduation_enclosure_card-256939084800706298',
 'https://www.zazzle.com/black_bow_grad_graduation_qr_code_college_fund_enclosure_card-256003506580221890',
 'https://www.zazzle.com/trendy_red_bow_ribbon_4_photo_graduation_party_invitation-256938330490029190',
 'https://www.zazzle.com/modern_doodle_blue_bow_graduation_party_invitation-256721498297147388',
 'https://www.zazzle.com/modern_elegant_trendy_purple_bow_graduation_invitation-256783781082813323',
 'https://www.zazzle.com/elegant_black_bow_graduation_party_invitation-256739710782542684',
 'https://www.zazzle.com/pink_bow_in_her_grad_era_elegant_photo_graduation_invitation-256372786085047327',
 'https://www.zazzle.com/vintage_pink_bow_arch_photo_graduation_announcement-256727968294365221',
 'https://www.zazzle.com/blush_pink_bow_graduation_party_invitation-256714191294183536',
 'https://www.zazzle.com/modern_arch_photo_graduation_party_invitation-256208634520119362',
 'https://www.zazzle.com/trendy_blue_bow_ribbon_4_photo_graduation_party_invitation-256072373722002592',
 'https://www.zazzle.com/trendy_neutral_bow_ribbon_4_photo_graduation_party_invitation-256076214082533936',
 'https://www.zazzle.com/modern_pink_bow_graduation_advice_and_wishes_enclosure_card-256747683859340684',
 'https://www.zazzle.com/wildflower_bow_graduation_invitation-256992532423494035',
 'https://www.zazzle.com/modern_elegant_trendy_stylish_black_bow_graduation_invitation-256276749866959642',
 'https://www.zazzle.com/she_did_it_graduation_party_invitation-256612056570150148',
 'https://www.zazzle.com/black_bow_photo_graduation_invitation-256829759931331209',
 'https://www.zazzle.com/wildflower_graduation_sign-256897701187345718',
 'https://www.zazzle.com/black_bow_pink_grad_party_invitation-256480668584007027',
 'https://www.zazzle.com/modern_elegant_trendy_stylish_pink_bow_graduation_invitation-256420710671822572']

# Scraping Data From Each Prodcut

In [ ]:
s=Service("C:/Users/Tanvir Ahmed/Downloads/chromedriver-win64/chromedriver.exe")
driver = webdriver.Chrome(service=s)

title=[]
view=[]
created_date=[]
tag=[]

wait = WebDriverWait(driver, 10) #set a waiter

for i in link:
    driver.get(i) #visiting each link

    # wait until page loads the title
    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, "ProductSpaceDetailsPod_title")))
    except:
        print(f"Page not loaded properly: {i}")
        continue
    #scroll to the end of the page
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
    
    #wait until page loads the OtherInfo block
    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, "OtherInfo")))
    except:
        print(f"Page not loaded properly: {i}")
        continue    

    #after loead all information get the source html of the page
    html=driver.page_source

    #now I can convert it to a soup object and then parse it to get all information
    soup=BeautifulSoup(html,'lxml')

    #get the title
    try:
        t = soup.find('h1', {'class': 'ProductSpaceDetailsPod_title'}).text.strip()
    except:
        t = None
    title.append(t)

    #get the total views
    try:
        v = soup.find('div', {'class': 'BehavioralCallout_copy'}).find_all('div')[1].text.strip()
    except:
        v = None
    view.append(v)

    #get the created on date
    try:
        d = soup.find('div', {'class': 'OtherInfo'}).find_all('div')[1].find('span').text.strip()
    except:
        d = None
    created_date.append(d)

    #get all tags and merge them into a string
    try:
        all_tags = soup.find('div', {'class': 'Tags-tagsList'}).find_all('span')
        s = [tg.text.strip() for tg in all_tags]
        s = ", ".join(s)
    except:
        s = None
    tag.append(s)

#close browser
driver.quit()

#store those data into a dataframe
df=pd.DataFrame({
    "Link":link,
    'Title':title,
    'View':view,
    'Created Date':created_date,
    'Tag':tag
})

In [ ]:
#making backups
df_original=df.copy()

# Data Cleaning

In [108]:
#converting the date to datetime format and sort the dataframe on date ( resent product comes first)
df["Created Date"] = pd.to_datetime(
    df["Created Date"],
    format="%m/%d/%Y, %I:%M %p",
    errors="coerce"
)
df = df.sort_values(by="Created Date", ascending=False)
df

,Link,Title,View,Created Date,Tag
53,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,28 people viewed this design,2026-03-20 13:18:00,"graduation daughter, coquette invite, arch pho..."
7,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower Bow Graduation party Photo Collage ...,612 people viewed this design,2026-03-14 02:32:00,"graduation party, grad, wildflower, floral, gi..."
57,https://www.zazzle.com/wildflower_graduation_s...,Wildflower Graduation Sign,40 people viewed this design,2026-03-03 05:04:00,"wildflower graduation invitation, pink bow, gr..."
55,https://www.zazzle.com/she_did_it_graduation_p...,She Did It! Graduation Party Invitation,37 people viewed this design,2026-03-02 15:13:00,"chic party invitations for her, elegant party ..."
9,https://www.zazzle.com/black_bow_photo_graduat...,Black Bow Photo Graduation Invitation,364 people viewed this design,2026-02-24 17:48:00,"graduation daughter, coquette invite, arch pho..."
21,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,194 people viewed this design,2026-02-24 17:22:00,"graduation daughter, coquette invite, elegant ..."
17,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,189 people viewed this design,2026-02-24 16:12:00,"graduation daughter, coquette invite, arch pho..."
39,https://www.zazzle.com/wildflower_graduation_p...,Wildflower Graduation Party Return Address Label,45 people viewed this design,2026-02-24 00:01:00,"graduation invitation, wildflower, floral, gra..."
46,https://www.zazzle.com/pink_bow_in_her_grad_er...,Pink Bow In Her Grad Era Elegant Photo Graduat...,176 people viewed this design,2026-02-19 02:40:00,"pink bow graduation party invitation, in her g..."
56,https://www.zazzle.com/black_bow_photo_graduat...,Black Bow Photo Graduation Invitation,221 people viewed this design,2026-02-05 22:57:00,"black bow graduation, graduation daughter, coq..."
3,https://www.zazzle.com/trendy_modern_photo_gra...,Trendy Modern Photo Graduation Invitation,622 people viewed this design,2026-01-29 04:25:00,"arch graduation invitation, photo, pink bow, h..."
5,https://www.zazzle.com/arch_pink_bow_photo_gra...,Arch Pink Bow Photo Graduation Party Invitation,904 people viewed this design,2026-01-29 04:14:00,"arch graduation invitation, photo, pink bow, s..."
28,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Invitation,371 people viewed this design,2026-01-28 23:08:00,"pink bow graduation, graduation daughter, coqu..."
49,https://www.zazzle.com/modern_arch_photo_gradu...,Modern Arch Photo Graduation Party Invitation,69 people viewed this design,2026-01-28 05:21:00,"arch graduation invitation, photo, bow, she di..."
2,https://www.zazzle.com/wildflower_pink_bow_gra...,Wildflower Pink Bow Graduation Invitation,2.6K people viewed this design,2026-01-27 05:58:00,"grandmillennial graduation invitation, pink bo..."
10,https://www.zazzle.com/pink_bow_graduation_inv...,Pink Bow Graduation Invitation,566 people viewed this design,2026-01-27 05:26:00,"grandmillennial graduation invitation, pink bo..."
30,https://www.zazzle.com/sweet_pinstriped_black_...,Sweet Pinstriped Black Bow Graduation Invitation,235 people viewed this design,2026-01-23 16:24:00,"class of 2026, trendy, graduate, graduated, se..."
12,https://www.zazzle.com/modern_class_of_2026_ph...,Modern Class of 2026 Photo Graduation Party In...,2.5K people viewed this design,2026-01-12 14:59:00,"graduation, graduation party, photo graduation..."
11,https://www.zazzle.com/modern_elegant_blue_bow...,Modern Elegant Blue Bow Arch Photo Graduation ...,519 people viewed this design,2026-01-12 13:31:00,"graduation, graduation party, photo graduation..."
34,https://www.zazzle.com/coquette_pink_bow_shabb...,Coquette Pink Bow Shabby Chic Graduation Party...,402 people viewed this design,2025-08-22 07:56:00,"watercolor coquette bow, elegant pink rose wal..."
38,https://www.zazzle.com/gold_and_black_coquette...,Gold and Black Coquette Nurse Graduation RN In...,940 people viewed this design,2025-04-27 11:46:00,"nurse graduation party invitation, coquette bo..."
20,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Party Invitation,268 people viewed this design,2025-04-07 16:37:00,"class of 2026, graduation party invitations, b..."
52,https://www.zazzle.com/modern_pink_bow_graduat...,Modern Pink Bow Graduation Advice And Wishes E...,110 people viewed this design,2025-04-01 06:41:00,"elegant watercolor blush pink bow, modern eleg..."
40,https://www.zazzle.com/modern_pink_bow_qr_code...,Modern Pink Bow QR Code College Fund Graduatio...,115 people viewed this design,2025-03-31 14:40:00,"class of 2025 trendy stylish, high school or c..."
58,https://www.zazzle.com/black_bow_pink_grad_par...,Black Bow Pink Grad Party Invitation,387 people viewed this design,2025-03-24 18:44:00,"pink and black grad, black bow, photo graduati..."
48,https://www.zazzle.com/blush_pink_bow_graduati...,Blush Pink Bow Graduation Party Invitation,188 people viewed this design,2025-03-22 10:48:00,"pink bow graduation invitation, photo grad par..."
4,https://www.zazzle.com/elegant_black_bow_photo...,Elegant Black Bow Photo Grad Party Invitation,1.5K people viewed this design,2025-03-22 08:57:00,"black and white typography grad, black bow, ph..."
41,https://www.zazzle.com/black_bow_grad_graduati...,Black Bow Grad Graduation QR Code College Fund...,339 people viewed this design,2025-03-20 15:49:00,"grad, black coquette bow, minimalist, modern, ..."
0,https://www.zazzle.com/pink_bow_photo_2025_gra...,Pink Bow Photo 2025 Graduation Invitation,5.2K people viewed this design,2025-03-19 15:26:00,"pink bow graduation, graduation daughter, coqu..."
13,https://www.zazzle.com/wildflower_pink_bow_gra...,Wildflower Pink Bow Graduation Party Invitation,1.3K people viewed this design,2025-03-19 02:18:00,"floral, wildflower, chic, girl, graduation, gr..."
24,https://www.zazzle.com/pink_bow_coquette_gradu...,Pink Bow Coquette Graduation Cap Thank You C...,176 people viewed this design,2025-03-16 15:32:00,"bow graduation thank you card, class of 2025 m..."
32,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,156 people viewed this design,2025-03-15 14:12:00,"graduation, bow graduation, coquette, bow, bla..."
27,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,391 people viewed this design,2025-03-15 14:10:00,"graduation, bow graduation, coquette, bow, bla..."
22,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,1K people viewed this design,2025-03-15 13:38:00,"graduation, bow graduation, coquette, bow, bla..."
37,https://www.zazzle.com/elegant_coquette_bow_gr...,Elegant Coquette Bow Graduation 3 Photos Invit...,131 people viewed this design,2025-03-13 17:40:00,"pink graduation invite, coquette bow graduatio..."
14,https://www.zazzle.com/pink_bow_three_photo_gr...,Pink Bow Three Photo Graduation 2025 Invitation,329 people viewed this design,2025-03-11 07:41:00,"graduation invitation 2025, class of 2025, gar..."
6,https://www.zazzle.com/modern_trendy_pink_bow_...,Modern Trendy Pink Bow Graduation Cap Graduati...,622 people viewed this design,2025-03-06 05:11:00,"high school college graduate university, casua..."
8,https://www.zazzle.com/modern_elegant_pink_bow...,Modern Elegant Pink Bow Graduation Cap Gradua...,855 people viewed this design,2025-03-05 14:29:00,"graduation invitations announcements, high sch..."
47,https://www.zazzle.com/vintage_pink_bow_arch_p...,Vintage Pink Bow Arch Photo Graduation Announc...,158 people viewed this design,2025-03-05 00:27:00,"coquette, photo graduation announcements, arch..."
31,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Black Bow Gradua...,310 people viewed this design,2025-02-27 03:59:00,"graduation invitations announcements, high sch..."
33,https://www.zazzle.com/blue_coquette_nurse_gra...,Blue Coquette Nurse Graduation Invitation,295 people viewed this design,2025-02-26 13:26:00,"nurse graduation party invitation, coquette bo..."
43,https://www.zazzle.com/modern_doodle_blue_bow_...,Modern Doodle Blue Bow Graduation Party Invita...,53 people viewed this design,2025-02-22 19:43:00,"class of 2026, doodle graduation invitation, g..."
19,https://www.zazzle.com/pink_bow_vertical_scrip...,Pink Bow Vertical Script Graduation Invitation,747 people viewed this design,2025-02-11 21:12:00,"modern minimal elegant, handwritten calligraph..."
1,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Party Invitation,4K people viewed this design,2025-02-07 05:44:00,"pink bow graduation invitation, photo grad par..."
26,https://www.zazzle.com/pink_coquette_bow_gradu...,Pink Coquette Bow Graduation Party Invitation,6.3K people viewed this design,2025-01-17 20:23:00,"pink bow graduation invite, coquette bow gradu..."
44,https://www.zazzle.com/modern_elegant_trendy_p...,Modern Elegant Trendy Purple Bow Graduation In...,297 people viewed this design,2025-01-15 02:09:00,"graduation invitations announcements, class of..."
15,https://www.zazzle.com/modern_elegant_trendy_p...,Modern Elegant Trendy Pink Bow Photo Graduatio...,1.1K people viewed this design,2025-01-15 01:54:00,"graduation invitations announcements, class of..."
59,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Pink Bow Graduat...,1.5K people viewed this design,2025-01-15 01:50:00,"graduation invitations announcements, class of..."
45,https://www.zazzle.com/elegant_black_bow_gradu...,Elegant Black Bow Graduation Party Invitation,870 people viewed this design,2025-01-14 22:09:00,"elegant, chic, coquette, black bow, elegant ca..."
36,https://www.zazzle.com/elegant_red_bow_graduat...,Elegant Red Bow Graduation Party Invitation,323 people viewed this design,2025-01-14 00:13:00,"class of 2026, graduation party invitations, g..."
25,https://www.zazzle.com/pink_coquette_nurse_gra...,Pink Coquette Nurse Graduation Invitation,2.5K people viewed this design,2025-01-10 20:57:00,"nurse graduation party invitation, pink bow nu..."
35,https://www.zazzle.com/trendy_pink_bow_photo_g...,Trendy Pink Bow Photo Graduation Invitation,1.4K people viewed this design,2025-01-05 00:58:00,"class of 2026, modern, trendy, stylish, gradua..."
16,https://www.zazzle.com/elegant_blue_hydrangea_...,Elegant Blue Hydrangea Bow Ribbon Graduation P...,1K people viewed this design,2024-12-28 10:57:00,"minimalist wildflower modern blossom, wild flo..."
42,https://www.zazzle.com/trendy_red_bow_ribbon_4...,Trendy Red Bow Ribbon 4 PHOTO Graduation Party...,96 people viewed this design,2024-12-26 04:29:00,"grad party, modern, elegant minimalist, scribb..."
51,https://www.zazzle.com/trendy_neutral_bow_ribb...,Trendy Neutral Bow Ribbon 4 PHOTO Graduation P...,323 people viewed this design,2024-12-26 03:30:00,"grad party, modern, elegant minimalist, spring..."
29,https://www.zazzle.com/trendy_black_bow_ribbon...,Trendy Black Bow Ribbon 5 PHOTO Graduation Par...,320 people viewed this design,2024-12-26 03:06:00,"grad party, modern, elegant minimalist, multic..."
50,https://www.zazzle.com/trendy_blue_bow_ribbon_...,Trendy Blue Bow Ribbon 4 PHOTO Graduation Part...,347 people viewed this design,2024-12-24 21:37:00,"grad party, modern, elegant minimalist, scribb..."
23,https://www.zazzle.com/trendy_pink_bow_coquett...,Trendy Pink Bow Coquette 5 PHOTO Graduation Pa...,428 people viewed this design,2024-12-21 11:38:00,"grad party, modern, elegant minimalist, bow ri..."
54,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Black Bow Gradua...,1.1K people viewed this design,2024-12-19 16:58:00,"elegant watercolor black and white, graduation..."
18,https://www.zazzle.com/ribbon_graduation_3_let...,Ribbon Graduation | 3 Letter Pink Monogram Cre...,376 people viewed this design,2024-05-25 03:32:00,"graduates, graduation, graduation cap, waterco..."

In [ ]:
# make the view column better, string to number
def string_to_int(text):
    match = re.search(r"\d+(\.\d+)?", str(text)) #search for the number
    
    if not match:
        return None
    
    number = float(match.group()) #extract the number
    
    if "K" in str(text): #if there any "K" in the string mulply the number with 1000
        return int(number * 1000)
    else:
        return int(number)

In [110]:
df['View']=df['View'].apply(string_to_int)

# End

## Making a Frequency Table for the Tags

In [ ]:
tag_df = (
    df["Tag"]
    .str.split(", ") #split the tags from a single string to array of tags
    .explode() #flatten the tags, from array to each tags at a line
    .value_counts() #calculate the frequency count
)

In [140]:
tag_df.head(60)

Tag
modern                                     17
coquette                                   14
trendy                                     14
class of 2026                              14
grad party                                 14
arch photo                                 13
graduate                                   12
graduation                                 10
calligraphy script typography classy        9
elegant                                     9
high school college                         8
pink bow                                    8
bow                                         8
high school college graduate university     8
graduation invitations announcements        7
casual minimalist simple grad party         7
coquette invite                             7
graduation daughter                         7
elegant bow                                 7
graduation party                            7
high school or college                      6
floral                                      6
chic graduation announcement cards          6
black bow                                   5
funky hand drawn                            5
college                                     5
high school                                 5
elegant minimalist                          5
elegant watercolor blush pink bow           5
class of 2025 trendy stylish                4
coquette ribbon pink senior graduation      4
graduation party invitation                 4
wildflower                                  4
class of 2025                               4
bow theme                                   4
vintage                                     4
university graduate                         4
modern elegant stylish trendy formal        4
pink                                        4
simple trendy script                        4
stylish font                                4
whimsical floral graduation                 4
calligraphy                                 4
class of 2024 2025 2026                     4
modern minimal elegant                      3
wildflowers                                 3
multicolor wildflowers                      3
2026 graduation party                       3
modern elegant glass of 2026                3
photo graduation party                      3
arch graduation invitation                  3
bow and ribbon                              3
graduation party invitations                3
she earned it graduation invitation         3
coquette nurse graduation invitation        3
nurse graduation party invite               3
photo                                       3
black and white                             3
daughter                                    3
bow graduation                              3
Name: count, dtype: int64

In [ ]:
#now using that frequency table assigning those frequency value to each tags on the dataframe also assign the total frequency count at the end of the each product's tag
tag_dict = tag_df.to_dict()
def tag_with_freq_and_total(tag_string):
    tags = [t.strip() for t in tag_string.split(",")] #converting string to list of tags
    
    counts = [tag_dict.get(tag, 0) for tag in tags] #getting the freq count for each tags and store it in a list
    
    # tag + freq
    tag_freq = [f"{tag} {count}" for tag, count in zip(tags, counts)] # assining the frequency count along with each tag
    
    total = sum(counts)
    
    return ", ".join(tag_freq) + f" | Total: {total}" #returting the final string with total counts

In [143]:
df["Tag_with_freq"] = df["Tag"].apply(tag_with_freq_and_total)
df

,Link,Title,View,Created Date,Tag,Tag_with_freq
53,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,28,2026-03-20 13:18:00,"graduation daughter, coquette invite, arch pho...","graduation daughter 7, coquette invite 7, arch..."
7,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower Bow Graduation party Photo Collage ...,612,2026-03-14 02:32:00,"graduation party, grad, wildflower, floral, gi...","graduation party 7, grad 2, wildflower 4, flor..."
57,https://www.zazzle.com/wildflower_graduation_s...,Wildflower Graduation Sign,40,2026-03-03 05:04:00,"wildflower graduation invitation, pink bow, gr...","wildflower graduation invitation 1, pink bow 8..."
55,https://www.zazzle.com/she_did_it_graduation_p...,She Did It! Graduation Party Invitation,37,2026-03-02 15:13:00,"chic party invitations for her, elegant party ...","chic party invitations for her 1, elegant part..."
9,https://www.zazzle.com/black_bow_photo_graduat...,Black Bow Photo Graduation Invitation,364,2026-02-24 17:48:00,"graduation daughter, coquette invite, arch pho...","graduation daughter 7, coquette invite 7, arch..."
21,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,194,2026-02-24 17:22:00,"graduation daughter, coquette invite, elegant ...","graduation daughter 7, coquette invite 7, eleg..."
17,https://www.zazzle.com/wildflower_bow_graduati...,Wildflower & Bow Graduation Invitation,189,2026-02-24 16:12:00,"graduation daughter, coquette invite, arch pho...","graduation daughter 7, coquette invite 7, arch..."
39,https://www.zazzle.com/wildflower_graduation_p...,Wildflower Graduation Party Return Address Label,45,2026-02-24 00:01:00,"graduation invitation, wildflower, floral, gra...","graduation invitation 1, wildflower 4, floral ..."
46,https://www.zazzle.com/pink_bow_in_her_grad_er...,Pink Bow In Her Grad Era Elegant Photo Graduat...,176,2026-02-19 02:40:00,"pink bow graduation party invitation, in her g...","pink bow graduation party invitation 1, in her..."
56,https://www.zazzle.com/black_bow_photo_graduat...,Black Bow Photo Graduation Invitation,221,2026-02-05 22:57:00,"black bow graduation, graduation daughter, coq...","black bow graduation 1, graduation daughter 7,..."
3,https://www.zazzle.com/trendy_modern_photo_gra...,Trendy Modern Photo Graduation Invitation,622,2026-01-29 04:25:00,"arch graduation invitation, photo, pink bow, h...","arch graduation invitation 3, photo 3, pink bo..."
5,https://www.zazzle.com/arch_pink_bow_photo_gra...,Arch Pink Bow Photo Graduation Party Invitation,904,2026-01-29 04:14:00,"arch graduation invitation, photo, pink bow, s...","arch graduation invitation 3, photo 3, pink bo..."
28,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Invitation,371,2026-01-28 23:08:00,"pink bow graduation, graduation daughter, coqu...","pink bow graduation 2, graduation daughter 7, ..."
49,https://www.zazzle.com/modern_arch_photo_gradu...,Modern Arch Photo Graduation Party Invitation,69,2026-01-28 05:21:00,"arch graduation invitation, photo, bow, she di...","arch graduation invitation 3, photo 3, bow 8, ..."
2,https://www.zazzle.com/wildflower_pink_bow_gra...,Wildflower Pink Bow Graduation Invitation,2600,2026-01-27 05:58:00,"grandmillennial graduation invitation, pink bo...","grandmillennial graduation invitation 2, pink ..."
10,https://www.zazzle.com/pink_bow_graduation_inv...,Pink Bow Graduation Invitation,566,2026-01-27 05:26:00,"grandmillennial graduation invitation, pink bo...","grandmillennial graduation invitation 2, pink ..."
30,https://www.zazzle.com/sweet_pinstriped_black_...,Sweet Pinstriped Black Bow Graduation Invitation,235,2026-01-23 16:24:00,"class of 2026, trendy, graduate, graduated, se...","class of 2026 14, trendy 14, graduate 12, grad..."
12,https://www.zazzle.com/modern_class_of_2026_ph...,Modern Class of 2026 Photo Graduation Party In...,2500,2026-01-12 14:59:00,"graduation, graduation party, photo graduation...","graduation 10, graduation party 7, photo gradu..."
11,https://www.zazzle.com/modern_elegant_blue_bow...,Modern Elegant Blue Bow Arch Photo Graduation ...,519,2026-01-12 13:31:00,"graduation, graduation party, photo graduation...","graduation 10, graduation party 7, photo gradu..."
34,https://www.zazzle.com/coquette_pink_bow_shabb...,Coquette Pink Bow Shabby Chic Graduation Party...,402,2025-08-22 07:56:00,"watercolor coquette bow, elegant pink rose wal...","watercolor coquette bow 1, elegant pink rose w..."
38,https://www.zazzle.com/gold_and_black_coquette...,Gold and Black Coquette Nurse Graduation RN In...,940,2025-04-27 11:46:00,"nurse graduation party invitation, coquette bo...","nurse graduation party invitation 3, coquette ..."
20,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Party Invitation,268,2025-04-07 16:37:00,"class of 2026, graduation party invitations, b...","class of 2026 14, graduation party invitations..."
52,https://www.zazzle.com/modern_pink_bow_graduat...,Modern Pink Bow Graduation Advice And Wishes E...,110,2025-04-01 06:41:00,"elegant watercolor blush pink bow, modern eleg...","elegant watercolor blush pink bow 5, modern el..."
40,https://www.zazzle.com/modern_pink_bow_qr_code...,Modern Pink Bow QR Code College Fund Graduatio...,115,2025-03-31 14:40:00,"class of 2025 trendy stylish, high school or c...","class of 2025 trendy stylish 4, high school or..."
58,https://www.zazzle.com/black_bow_pink_grad_par...,Black Bow Pink Grad Party Invitation,387,2025-03-24 18:44:00,"pink and black grad, black bow, photo graduati...","pink and black grad 1, black bow 5, photo grad..."
48,https://www.zazzle.com/blush_pink_bow_graduati...,Blush Pink Bow Graduation Party Invitation,188,2025-03-22 10:48:00,"pink bow graduation invitation, photo grad par...","pink bow graduation invitation 2, photo grad p..."
4,https://www.zazzle.com/elegant_black_bow_photo...,Elegant Black Bow Photo Grad Party Invitation,1500,2025-03-22 08:57:00,"black and white typography grad, black bow, ph...","black and white typography grad 1, black bow 5..."
41,https://www.zazzle.com/black_bow_grad_graduati...,Black Bow Grad Graduation QR Code College Fund...,339,2025-03-20 15:49:00,"grad, black coquette bow, minimalist, modern, ...","grad 2, black coquette bow 1, minimalist 2, mo..."
0,https://www.zazzle.com/pink_bow_photo_2025_gra...,Pink Bow Photo 2025 Graduation Invitation,5200,2025-03-19 15:26:00,"pink bow graduation, graduation daughter, coqu...","pink bow graduation 2, graduation daughter 7, ..."
13,https://www.zazzle.com/wildflower_pink_bow_gra...,Wildflower Pink Bow Graduation Party Invitation,1300,2025-03-19 02:18:00,"floral, wildflower, chic, girl, graduation, gr...","floral 6, wildflower 4, chic 2, girl 1, gradua..."
24,https://www.zazzle.com/pink_bow_coquette_gradu...,Pink Bow Coquette Graduation Cap Thank You C...,176,2025-03-16 15:32:00,"bow graduation thank you card, class of 2025 m...","bow graduation thank you card 1, class of 2025..."
32,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,156,2025-03-15 14:12:00,"graduation, bow graduation, coquette, bow, bla...","graduation 10, bow graduation 3, coquette 14, ..."
27,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,391,2025-03-15 14:10:00,"graduation, bow graduation, coquette, bow, bla...","graduation 10, bow graduation 3, coquette 14, ..."
22,https://www.zazzle.com/modern_trendy_black_bow...,Modern Trendy Black Bow Graduation Party Invi...,1000,2025-03-15 13:38:00,"graduation, bow graduation, coquette, bow, bla...","graduation 10, bow graduation 3, coquette 14, ..."
37,https://www.zazzle.com/elegant_coquette_bow_gr...,Elegant Coquette Bow Graduation 3 Photos Invit...,131,2025-03-13 17:40:00,"pink graduation invite, coquette bow graduatio...","pink graduation invite 1, coquette bow graduat..."
14,https://www.zazzle.com/pink_bow_three_photo_gr...,Pink Bow Three Photo Graduation 2025 Invitation,329,2025-03-11 07:41:00,"graduation invitation 2025, class of 2025, gar...","graduation invitation 2025 1, class of 2025 4,..."
6,https://www.zazzle.com/modern_trendy_pink_bow_...,Modern Trendy Pink Bow Graduation Cap Graduati...,622,2025-03-06 05:11:00,"high school college graduate university, casua...","high school college graduate university 8, cas..."
8,https://www.zazzle.com/modern_elegant_pink_bow...,Modern Elegant Pink Bow Graduation Cap Gradua...,855,2025-03-05 14:29:00,"graduation invitations announcements, high sch...","graduation invitations announcements 7, high s..."
47,https://www.zazzle.com/vintage_pink_bow_arch_p...,Vintage Pink Bow Arch Photo Graduation Announc...,158,2025-03-05 00:27:00,"coquette, photo graduation announcements, arch...","coquette 14, photo graduation announcements 1,..."
31,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Black Bow Gradua...,310,2025-02-27 03:59:00,"graduation invitations announcements, high sch...","graduation invitations announcements 7, high s..."
33,https://www.zazzle.com/blue_coquette_nurse_gra...,Blue Coquette Nurse Graduation Invitation,295,2025-02-26 13:26:00,"nurse graduation party invitation, coquette bo...","nurse graduation party invitation 3, coquette ..."
43,https://www.zazzle.com/modern_doodle_blue_bow_...,Modern Doodle Blue Bow Graduation Party Invita...,53,2025-02-22 19:43:00,"class of 2026, doodle graduation invitation, g...","class of 2026 14, doodle graduation invitation..."
19,https://www.zazzle.com/pink_bow_vertical_scrip...,Pink Bow Vertical Script Graduation Invitation,747,2025-02-11 21:12:00,"modern minimal elegant, handwritten calligraph...","modern minimal elegant 3, handwritten calligra..."
1,https://www.zazzle.com/pink_bow_photo_graduati...,Pink Bow Photo Graduation Party Invitation,4000,2025-02-07 05:44:00,"pink bow graduation invitation, photo grad par...","pink bow graduation invitation 2, photo grad p..."
26,https://www.zazzle.com/pink_coquette_bow_gradu...,Pink Coquette Bow Graduation Party Invitation,6300,2025-01-17 20:23:00,"pink bow graduation invite, coquette bow gradu...","pink bow graduation invite 1, coquette bow gra..."
44,https://www.zazzle.com/modern_elegant_trendy_p...,Modern Elegant Trendy Purple Bow Graduation In...,297,2025-01-15 02:09:00,"graduation invitations announcements, class of...","graduation invitations announcements 7, class ..."
15,https://www.zazzle.com/modern_elegant_trendy_p...,Modern Elegant Trendy Pink Bow Photo Graduatio...,1100,2025-01-15 01:54:00,"graduation invitations announcements, class of...","graduation invitations announcements 7, class ..."
59,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Pink Bow Graduat...,1500,2025-01-15 01:50:00,"graduation invitations announcements, class of...","graduation invitations announcements 7, class ..."
45,https://www.zazzle.com/elegant_black_bow_gradu...,Elegant Black Bow Graduation Party Invitation,870,2025-01-14 22:09:00,"elegant, chic, coquette, black bow, elegant ca...","elegant 9, chic 2, coquette 14, black bow 5, e..."
36,https://www.zazzle.com/elegant_red_bow_graduat...,Elegant Red Bow Graduation Party Invitation,323,2025-01-14 00:13:00,"class of 2026, graduation party invitations, g...","class of 2026 14, graduation party invitations..."
25,https://www.zazzle.com/pink_coquette_nurse_gra...,Pink Coquette Nurse Graduation Invitation,2500,2025-01-10 20:57:00,"nurse graduation party invitation, pink bow nu...","nurse graduation party invitation 3, pink bow ..."
35,https://www.zazzle.com/trendy_pink_bow_photo_g...,Trendy Pink Bow Photo Graduation Invitation,1400,2025-01-05 00:58:00,"class of 2026, modern, trendy, stylish, gradua...","class of 2026 14, modern 17, trendy 14, stylis..."
16,https://www.zazzle.com/elegant_blue_hydrangea_...,Elegant Blue Hydrangea Bow Ribbon Graduation P...,1000,2024-12-28 10:57:00,"minimalist wildflower modern blossom, wild flo...","minimalist wildflower modern blossom 1, wild f..."
42,https://www.zazzle.com/trendy_red_bow_ribbon_4...,Trendy Red Bow Ribbon 4 PHOTO Graduation Party...,96,2024-12-26 04:29:00,"grad party, modern, elegant minimalist, scribb...","grad party 14, modern 17, elegant minimalist 5..."
51,https://www.zazzle.com/trendy_neutral_bow_ribb...,Trendy Neutral Bow Ribbon 4 PHOTO Graduation P...,323,2024-12-26 03:30:00,"grad party, modern, elegant minimalist, spring...","grad party 14, modern 17, elegant minimalist 5..."
29,https://www.zazzle.com/trendy_black_bow_ribbon...,Trendy Black Bow Ribbon 5 PHOTO Graduation Par...,320,2024-12-26 03:06:00,"grad party, modern, elegant minimalist, multic...","grad party 14, modern 17, elegant minimalist 5..."
50,https://www.zazzle.com/trendy_blue_bow_ribbon_...,Trendy Blue Bow Ribbon 4 PHOTO Graduation Part...,347,2024-12-24 21:37:00,"grad party, modern, elegant minimalist, scribb...","grad party 14, modern 17, elegant minimalist 5..."
23,https://www.zazzle.com/trendy_pink_bow_coquett...,Trendy Pink Bow Coquette 5 PHOTO Graduation Pa...,428,2024-12-21 11:38:00,"grad party, modern, elegant minimalist, bow ri...","grad party 14, modern 17, elegant minimalist 5..."
54,https://www.zazzle.com/modern_elegant_trendy_s...,Modern Elegant Trendy Stylish Black Bow Gradua...,1100,2024-12-19 16:58:00,"elegant watercolor black and white, graduation...","elegant watercolor black and white 1, graduati..."
18,https://www.zazzle.com/ribbon_graduation_3_let...,Ribbon Graduation | 3 Letter Pink Monogram Cre...,376,2024-05-25 03:32:00,"graduates, graduation, graduation cap, waterco...","graduates 1, graduation 10, graduation cap 1, ..."

In [ ]:
df.to_csv("Bow Graduation Invitatoin.csv") #save it to a csv file